go-gorm/gen

- generator.go
- internal/check/gen_structs.go
支持binary和varbinary两种字段类型，之前的默认类型是string，这两种类型在go中更适合使用[]byte
我通过varbinary保存IP地址，但是生成的数据类型是string，导致net.IP不能直接保存到数据库
> feat: binary和varbinary类型字段默认类型从string改为[]byte类型

- generator.go
- internal/check/export.go
- internal/parser/parser.go
- internal/template/base.go
Cannot auto import when the same package name exists
gen 使用golang.org/x/tools/imports生成自动导入，在项目中存在多个同名包，并且有相同名字的结构体，imports无法自动处理，会出现导入缺失或导入错误的情况。
在提交中使用反射获取结构体的包路径，生成文件时填充到import ()里面。
例如项目结构如下
```text
./internal/models
./internal/models/v2
./internal/models/v2/man.go
./internal/models/man.go
./internal/models/dog.go
```
`./internal/models/v2/man.go`和`./internal/models/man.go`拥有相同的包名(models)，相同的结构体(Man)，imports无法正确处理导入关系。
> fix: Import error if same struct name exists

- README.ZH_CN.md
- README.md
Fix document references in README.
修复 README 中文档引用。
- Supplement the directory of the unit test, add Chinese translation for unit test
补充单元测试的目录并增加单元测试章节中文翻译
- Fix the reference path error of the document in the associated preloading
修复关联预加载中文档的引用路径错误
- Fix the format problem that there are no blank lines before and after some sample codes
修复部分示例代码前后无空行的格式问题
None.
> docs(readme): fix document references in READMES && Add translation for unit test

- generator.go
GenerateAllTable has opts args, but unuse it.
GenerateAllTable with FieldOpt
> fix: generator GenerateAllTable unuse opts

- README.ZH_CN.md
- README.md
- field_options.go
it looks like all `gen.Field...` are not tested?
close https://github.com/go-gorm/gen/issues/485
```golang
g.ApplyBasic(g.GenerateModelAs("chii_groups", "Group",
gen.FieldComment("grp_lastpost", "always 0"),
))
```
generate struct like this:
```golang
type Group struct {
GrpLastpost uint32        `gorm:"..."` // always 0
}
```
> feat: add `gen.FieldComment` to rewrite struct comment

- generator.go
- internal/parser/parser.go
- internal/parser/utils.go
Generator prints file with a call to golang.org/x/tools/imports.Process, which will guess missing imports for source file. If import statements are already specified, The time cost of imports.Process can be greatly reduced.
This PR copies all imports used in DIY interface method parameter type to the generated file header.
> feat: add imports from DIY interface package to accelerate imports.Process

- internal/generate/query.go
Set `field.Relation.relationship` to the value of `schema.Relationship.Type`.
When generating from model struct, generated `*Tx.Find` method on HasMany/ManyToMany Association only returns one result, due to the absense of relationship type info.
Example:
```go
package model
type A struct {
ID uint `gorm:"primaryKey"`
}
type B struct {
ID uint `gorm:"primaryKey"`
A  []A  `gorm:"many2many:b_a;"`
}
// ------------------------------------
package main
// ...
func main() {
// ...
g.ApplyBasic(&model.A{}, &model.B{})
g.Execute()
}
```
Before:
```go
func (a bATx) Find() (result *model.A, err error) {
return result, a.tx.Find(&result)
}
```
After:
```go
func (a bManyToManyATx) Find() (result []*model.A, err error) {
return result, a.tx.Find(&result)
}
```
> fix: set RelationshipType from schema

- internal/generate/export.go
- internal/generate/query.go
- internal/parser/export.go
`model.AddMethodOpt` can not work well if the method in main file, due to https://github.com/go-gorm/gen/blob/master/internal/parser/export.go#L103 fixed caller skip.
So let the external to set the caller compatible with the `AddMethodOpt`
Define method in main file
> fix: compatible with add method opt in main

- internal/generate/export.go
- internal/generate/query.go
ParseStructRelationShip used the cache for the parsed structures but did not use it and skipped the child relationships.
> fix: ParseStructRelationShip with cache

- generator.go
- internal/generate/query.go
- internal/model/base.go
- tests/.expect/dal_1/model/people.gen.go
- tests/.expect/dal_1/query/people.gen.go
- tests/.expect/dal_2/model/people.gen.go
- tests/.expect/dal_2/query/people.gen.go
- tests/tables.sql
* add `func (b *QueryStructMeta) ReviseFieldNameFor(keywords model.KeyWord)` that could specify keyword list
* add a new KeyWord `DOKeywords` contains `Alias, TableName, WithContext`
* apply `DOKeywords` every time call `(g *Generator) apply`
I have field named `alias` in my table, and it could not compile after generating query (conflict with `func Alias`).
Of course I could add things like `gen.FieldRename("alias", "ALIAS")` in my generating code, but I think it should work out of box.
> feat: escape query struct keywords

- .github/workflows/tests.yml
- go.mod
- go.sum
- helper/clause.go
- internal/generate/clause.go
- internal/generate/section.go
- internal/model/base.go
- tests/go.mod
You can use `trim clause` to remove the keywords at the beginning or end of a SQL segment, including `and`,`or`,`xor`,`,`
```go
type TrimTest interface {
// TestTrim
//
// select * from @@table where
//    {{trim}}
//        {{for _, name :=range list}}
//            name = @name or
//        {{end}}
//    {{end}}
TestTrim(list []string)[]gen.T
}
```
> feat：support trim clause

- generator.go
**不需要显示设置GOMAXPROCS，未设置时默认值就是runtime.NumCPU，设置后因为init的执行顺序会影响在容器中设置的环境变量**
GOMAXPROCS 是 Golang 提供的非常重要的一个环境变量设定。通过设定 GOMAXPROCS，可以调整 Runtime Scheduler 中 Processor（简称P）的数量。由于每个系统线程，必须要绑定 P 才能真正地进行执行。所以 P 的数量会很大程度上影响 Golang Runtime 的并发表现。GOMAXPROCS 一般的默认值是 CPU 核数，在容器中一般会通过 cgroup 等技术对 CPU 资源进行隔离。
**issues** https://github.com/go-gorm/gen/issues/851
>  fix setting GOMAXPROCS

- do.go
- interface.go
> Note: test suite pass but didn't add a new test. Tested the change in real application though.
Expose `DB.AddError()` to DAO interface. 
We build most of our queries using reusable `Scopes()` functions. In most cases the query validates few constraints and needs a way to propagate the error back.
> expose AddError via Dao interface

- internal/model/tbl_column.go
Fixes go-gorm/gen#918
Add check for `*` prefix in field type before applying nullable mask
Described in issue
> Clickhouse nullable fields support

- internal/generate/interface.go
This commit fixes a place where the method comment didn't match the definition due to a copy paste from its neighbor.
Background: I'm doing a research study on function comments that may be improvable. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!
> Fix copy paste mistake in method comment

- tools/gentool/gen.yml
- tools/gentool/gentool.go
1. append the `onlyModel` in `tools/gentool/gen.yml`
2. fix a table name input bug
set `tableList` content in cmdline, looks like this: `"users, orgs "`
then you get the `users.gen.go`, ` orgs .gen.go`(filename with a space in the first and last) after generate execution.
> FIX: input tablename with space

- tools/gentool/README.ZH_CN.md
- tools/gentool/README.md
- tools/gentool/gen.yml
- tools/gentool/gentool.go
`FieldCoverable` parameter exists, but it is missing in gentool. I added it.
refer:  https://gorm.io/gen/database_to_structs.html#Global-Generating-Options
> add fieldCoverable param to gentool

- internal/template/method.go
- internal/template/query.go
- tests/.expect/dal_2/query/banks.gen_test.go
- tests/.expect/dal_2/query/credit_cards.gen_test.go
- tests/.expect/dal_2/query/customers.gen_test.go
- tests/.expect/dal_2/query/gen_test.go
- tests/.expect/dal_2/query/people.gen_test.go
- tests/.expect/dal_2/query/users.gen_test.go
- tests/.expect/dal_3/query/banks.gen_test.go
- tests/.expect/dal_3/query/credit_cards.gen_test.go
- tests/.expect/dal_3/query/customers.gen_test.go
- tests/.expect/dal_3/query/gen_test.go
- tests/.expect/dal_3/query/people.gen_test.go
- tests/.expect/dal_3/query/users.gen_test.go
- tests/.expect/dal_4/query/banks.gen_test.go
- tests/.expect/dal_4/query/credit_cards.gen_test.go
- tests/.expect/dal_4/query/customers.gen_test.go
- tests/.expect/dal_4/query/gen_test.go
- tests/.expect/dal_4/query/people.gen_test.go
- tests/.expect/dal_4/query/users.gen_test.go
- tests/.expect/dal_5/query/gen_test.go
- tests/.expect/dal_5/query/users.gen_test.go
- tests/.expect/dal_6/query/gen_test.go
- tests/.expect/dal_6/query/users.gen_test.go
> feat: add prefix "_gent_test_" for test global var

- field/expr.go
suggest uppercase SQL function name
> style(field): use `CONCAT` with upper cases

- field/time.go
the unix timestamp is used in int64 rather than int. Int will only reach 2038.1.19
> feat(field): ppdate time.go FromUnixtime parameter int -> int64

- do.go
First and foremost, Thank you for creating this great project.
The issue where the context was always set to `context.Background()` in the UseDB method has been fixed. Previously, when performing database operations, the original context (including cancellation and timeout) was ignored, and a new `context.Background()` was always used. After the fix, the method now uses `db.Statement.Context` to propagate the existing context. If no context is set, it defaults to `context.Background()`.
In the following example, even though the context (ctx) was passed from the higher layer, the original context was not properly propagated in the previous implementation:
```go
t := query.Use(r.db.WithContext(ctx)).Tenant
tenant, err := t.Where(t.ID.Eq(id)).First()
```
By always setting the context to …
> fix: fix context propagation in UseDB method

- field/function.go
Added support for field.Func.Random() to enable compatibility with PostgreSQL.
This pull request introduces support for field.Func.Random(). Previously, `RAND()` was available through `field.Func.Rand()` (#901), which wasn’t compatible with PostgreSQL. This update makes it straightforward to use RANDOM() for PostgreSQL by `field.Func.Random()` in a similar manner.
> feat: support RANDOM()

- do.go
UpdateSimple, UpdateColumnSimple的columns参数传入nil时会panic, 希望和Where方法保持一致，生成clause时过滤掉nil
related issue:
https://github.com/go-gorm/gen/issues/1358
> feat: ignore nil AssignExpr
