go-gorm/gen

- field/base.go
- field/field_test.go
implement IsNull and IsNotNull method on field
```go
field.NewUint("user", "id").IsNull()
// `user`.`id` IS NULL
```
> feat: implement method of judging NULL

- internal/check/checkstruct.go
allow use gorm.Model cover duplicate member
> feat: cover duplicate member

- generator.go
rename ApplyByModel to ApplyInterfaces
> feat: rename ApplyByModel to ApplyInterfaces

- do.go
> feat: improve Where/Join implement

- generator.go
- go.mod
- go.sum
- internal/check/checkstruct.go
- internal/check/gen_structs.go
implement GenerateModelAs && refactor GenerateModel
> feat: implement GenerateModelAs && refactor GenerateModel

- do.go
- internal/template/tmpl.go
Complete all query methods in template
> Complete all query methods

- generator.go
- internal/check/checkinterface.go
- internal/check/clause.go
- internal/parser/parser.go
- internal/parser/utils.go
- internal/template/tmpl.go
> feat：conflict merge

- internal/check/checkinterface.go
- internal/parser/parser.go
> fix:param type

- internal/check/checkinterface.go
- internal/check/export.go
- internal/parser/export.go
- internal/parser/parser.go
- internal/template/tmpl.go
> fix:check result param type

- generator.go
- [] Tested
drop ApplyInterfaces API
> feat: drop ApplyInterfaces API

- do.go
- generator_test.go
- interface.go
- internal/template/tmpl.go
Refactor First/Take/Last/Find with reflect
> Refactor First/Take/Last/Find

- README.md
> feat: add interface method Doc

- helper/clause.go
> fix: trim set clause suffix ','

- internal/check/base.go
- internal/check/checkstruct.go
- internal/check/utils.go
> fix: change member gorm.Model to time.Time

- do.go
- do_test.go
- field/export.go
query accept user input tuple data
> feat: user input array

- generator.go
- internal/check/checkstruct.go
- internal/check/export.go
- internal/check/gen_structs.go
- internal/parser/parser.go
> feat: reuse gorm logger

- internal/check/checkstruct.go
fix: `time.Time` type mismatch
> fix: time type mismatch

- internal/check/base.go
- internal/check/checkstruct.go
> fix: gorm DeletedAt mismatch

- internal/check/checkstruct.go
- internal/check/gen_structs.go
- internal/check/utils.go
> feat: escape field keyword

- generator.go
- internal/check/checkinterface.go
- internal/check/checkstruct.go
- internal/check/export.go
- internal/parser/parser.go
> fix:duplicate method name 

- generator.go
- internal/check/checkinterface.go
- internal/check/export.go
> fix: duplicate method names 2

- do.go
- do_test.go
- field/field_test.go
- generator_test.go
> feat: remove model dependence

- field/expr.go
> feat: field expr add parentheses

- generator.go
> feat:split generated query code to file by table name

- internal/check/checkinterface.go
- internal/template/method.go
> feat:return single data use Take()

- generator.go
- internal/check/base.go
- internal/check/gen_structs.go
- internal/template/model.go
> feat: add gorm default tag

- internal/check/checkinterface.go
> feat: duplicate removal params

- internal/check/base.go
- internal/check/clause.go
> feat: template support array compared with nil

- README.md
- generator.go
- internal/check/base.go
- internal/check/gen_structs.go
> feat: model field nullable

- internal/check/checkinterface.go
- internal/template/method.go
> feat: change comment method to "//", support use hints

- internal/check/base.go
- internal/check/gen_structs.go
> feat: add pk tag

- README.md
- do.go
- errors.go
- field/association.go
- field/bool.go
- field/expr.go
- field/field.go
- field/float.go
- field/int.go
- field/string.go
- field/time.go
- interface.go
- internal/template/method.go
- support field set value with UpdateSimple
> feat: field set value

- README.md
- internal/check/checkinterface.go
// methodName descriptive message
//
// sql(select...)
func methodName() {
}
Change-Id: I097b96439ea0e30af79df2adea58a515ca0c8faa
- [] Tested
> [feat] support descriptive comment

- field/association.go
- field/export.go
- field/external_test.go
- field_options.go
- generator.go
- internal/check/checkstruct.go
- internal/check/gen_structs.go
- internal/template/struct.go
> perf: optimize relations create

- README.md
- field/external_test.go
- field/string.go
- implement sql function `FIND_IN_SET`
> feat(field): implement FindInSet/FindInSetWith

- do.go
- field_options.go
> doc(do): update doc about MemberOpt

- internal/check/checkstruct.go
> fix(generat): fix capturing iteration variables

- .github/dependabot.yml
- .github/workflows/reviewdog.yml
- .github/workflows/tests.yml
> feat(github): add github action

- internal/check/checkstruct.go
- internal/model/base.go
> feat(field): convert json.RawMessage/[]bytes to field.Bytes

- internal/template/method.go
> fix(template): FindInBatches with pointer

- README.md
- generator.go
- internal/check/gen_structs.go
- internal/model/db_conf.go
- internal/template/struct.go
> feat(generate): specify field generate with gorm type tag

- do.go
> fix(do): create new model when used

- internal/check/gen_structs.go
> feat(generate): new field name do not converted by NamingStrategy

- internal/template/struct.go
> feat(generate):ignore field without ColumnName in template

- internal/template/method.go
> feat(template): implement Method ScanByPage

- internal/template/method.go
> fix(generate): fix FindInBatches panic

- do.go
- interface.go
- internal/template/method.go
> feat(do): remove FindInBatch

- README.md
- generator.go
> feat(generate): implement new method `GenerateAllTable`

- README.md
- field_options.go
> feat(generate): custom tag

- internal/template/method.go
Unit test Ccverage increased to 92.5%
> feat(method):Add ScabByPage and As Uint Test.

- README.md
- field/export.go
- generator.go
- internal/check/gen_structs.go
- internal/model/base.go
- internal/model/db_conf.go
- internal/model/tb_column.go
> feat(generate): diy data mapping

- internal/model/base.go
- internal/model/tb_column.go
> fix(generate): fix type with nullable

- do.go
> fix(do): fix transaction get tableName

- internal/model/tb_column.go
> fix: auto increment tag

- field/expr.go
- field/field.go
- field/float.go
- field/int.go
- field/string.go
- field/time.go
> feat(field): add new method IFNULL

- do.go
> feat(do): distinct with expr

- field_options.go
- generator.go
- internal/check/gen_structs.go
- internal/model/db_conf.go
- internal/model/tb_column.go
> feat(generate): allow user specify tag name stragety

- internal/model/options.go
> feat: default schema name option

- internal/check/utils.go
> fix(generate): negative number are digit

- tools/gentool/README.ZH_CN.md
- tools/gentool/README.md
> feat(README):add gentool README.md

- README.md
- generator.go
- go.mod
- go.sum
- internal/check/checktest.go
- internal/template/base.go
- internal/template/method.go
- internal/template/query.go
- [] Tested
generate unit test for diy method, support diy testcase, testcase should be in the same package with test file
> generate unit test for diy method

- generator.go
> perf(generate): remove verbose operation

- README.ZH_CN.md
> fix(README.ZH_CN): Correct spelling errors

- README.ZH_CN.md
- README.md
* `feat` 更新 README.zh-cn.md 中的目录结构，保证 `TOC` 锚点与 README.md 一致，使用 `span>id` 跟踪 `TOC` 中内容，保证内容后续可通过锚点跟踪。
Update the directory structure in README.zh-cn.md to ensure that the anchor point of `TOC` is consistent with README.md, use `span>id` to track the content in `TOC`, and ensure that the content can be tracked through the anchor point.
* `feat` 完善目录结构中未完善的翻译内容
To improve the incomplete translation content in the directory structure
* `fix` 修正少量错别字和描述不严谨内容
Fix a few typos and inaccurate descriptions
* `fix` (url) 补充之前翻译导致丢失的 `内联条件查询（inline-condition）`
Add the `inline-condition` query that was lost due to previous translation
无。
None.
> docs(readme): revise and update the directory structure

- examples/main.go
> fix import

- generator.go
- internal/parser/parser.go
> feat: suppor return pointer

- README.ZH_CN.md
- README.md
> docs(readme): fix readme example

- sec_check.go
> feat(do): allow clause.Locking

- examples/README.md
- examples/cmd/ultimate/generate.go
- examples/cmd/without_db/generate.go
- examples/dal/model/model.go
- examples/generate.sh
> docs(example): add without db example

- do.go
> fix(do): Update Selected Fields

- README.ZH_CN.md
Improve the Chinese translation of README.ZH-CN.md
改进 README.ZH-CN.md 的中文翻译
Improved the Chinese translation of the following content:
改进了以下内容的中文翻译：
- Quick start
快速开始
- Field expressions
字段表达式
- Basic && Conditional queries
基本 && 条件查询
- Subquerie, transaction, and advanced querie
子查询、事务和高级查询
- Association
关联关系
- DIY methods, advanced-topics, and binary
DIY 方法、高级主题和二进制
- Contributing and license agreements
贡献和许可协议
None.
> dosc(readme-zh-cn): Improve the Chinese translation

- field/expr.go
- internal/template/struct.go
> feat(generate): GetFieldByName with method Desc

- internal/check/checkinterface.go
- internal/parser/parser.go
- internal/template/method.go
diy method input params support struct
```go
type SearchMethods interface{
//select * from @@table
//	{{where}}
//		{{if user.Name !=""}}
//			name = @user.Name
//		{{end}}
//		{{if user.Age>0}}
//			age = @user.Age
//		{{end}}
//	{{end}}
FindByUser(user Search.User) []gen.T
}
```
> feat：input param support struct

- internal/template/struct.go
> fix(generate): fix template duplicate name

- internal/check/checkinterface.go
- internal/template/method.go
> fix struct packagename

- generator.go
> feat(generat): only gen db model

- config.go
- generator.go
> feat(generate): format && do not generate query code without apply method

- README.ZH_CN.md
- README.md
- do.go
- field/association.go
> feat(generate): preload with offset and limit

- internal/template/method.go
- [] Tested
- 当limit=0的时候，查询sql就会吞掉limit，导致查询数据量很多。
> feat: findbypage增加limit=0的过滤

- internal/template/struct.go
> fix(generate): fix GetFieldByName panic

- internal/check/gen_structs.go
- internal/template/struct.go
> fix: column name prefix

- condition.go
- do.go
In an unthinking moment, when I use :
```go
dataList, err := dal.TableEntity.WithContext(ctx).Where(nil).Find()
```
the program panic in:
https://github.com/go-gorm/gen/blob/f9c21d3deef5609e456c9bd80d55ac16c71ea0a6/condition.go#L41
the code such as:
```go
for _, cond := range conds {
if err := cond.CondError(); err != nil {
return nil, err
}
... // some other logic
}
```
so I committed the PR to cover this little leak.
And I add the `len() = 0` to a new location after the function `condToExpression` 
so that we can filter out some illegal conditions  in the function `condToExpression`, in the future.
Yes, already local test
> feat: condition检查支持空值

- internal/check/checkinterface.go
- internal/check/clause.go
- internal/check/section.go
- internal/parser/parser.go
- internal/template/method.go
> fix：Execute SQL with none param

- generator.go
> feat(generate): parse table name with table prefix

- internal/check/checkinterface.go
> Fix:sql has @variable

- internal/check/clause.go
> fix：DIY SQL end add a space

- internal/check/checkinterface.go
- internal/check/clause.go
> feat:make sure only one space

- do.go
> fix(do): fix subquery scan panic

- generator.go
- internal/utils/pools/export.go
- internal/utils/pools/pool.go
> feat(generate): render concurrently

- helper/clause.go
- internal/check/checkinterface.go
- internal/check/clause.go
> Handled spaces

- internal/template/struct.go
> fix(generate): fix template

- config.go
- generator.go
> fix: model pkg path

- generator.go
> style(generate): change log level

- field/expr.go
- field/external_test.go
fix typo of function name that `GroutConcat` should be `GroupConcat`
> fix(field): typo GroutConcat should be GroupConcat

- README.ZH_CN.md
- README.md
- do.go
- field/association.go
> feat(field): preload with select

- field/export.go
> feat(field): add ALL

- generator.go
> sytle(generate): remove verbose log

- generator.go
> feat(generate): without empty query dir

- tools/gentool/README.ZH_CN.md
- tools/gentool/README.md
- tools/gentool/gentool.go
> feat(gentool): generate only model

- go.mod
- go.sum
> chore(deps): remove replace

- README.ZH_CN.md
- README.md
> 更新项目根目录里的README文件

- README.ZH_CN.md
- README.md
example of add 'group by and count'
look this Issues https://github.com/go-gorm/gen/issues/344
> docs(readme): example of add 'group by and count'

- do.go
> fix(do): group by expression

- do.go
> style(do): reuse underlyingDB

- do.go
> fix(do): fix updates model copy

- internal/check/checktest.go
- internal/parser/parser.go
> feat(generate): accept []interface{}

- internal/model/tbl_column.go
> fix(generate): created/updated_at without default

- internal/model/tbl_column.go
> fix(table): generate field with default value to pointer

- field/export_test.go
- field/field.go
> feat(field): method accept driver.Valuer

- internal/template/struct.go
> feat(generate): add Table method

- do.go
> feat(do): implement WithResult method

- export.go
- generator.go
> feat(field): export FieldOpt

- config.go
- generator.go
- internal/check/gen_structs.go
- internal/model/conf.go
- internal/model/tbl_column.go
> feat: add field coverable option

- README.ZH_CN.md
- README.md
Fix spell error.
Change from "necessray" to "necessary".
> docs: fix typo

- internal/model/tbl_column.go
- internal/template/method.go
> perf: optimize FindByPage

- internal/template/method.go
> feat: return count when limit == 0

- internal/check/tb_info.go
- internal/model/tbl_column.go
> fix: other driver

- internal/template/method.go
> fix: count without offset in FindByPage

- do.go
> fix: update table name in schema

- do.go
Description on Issue #389 
fix #389 
Use case description on Issue #389
> feat(Joins): implement Joins "ON" condition for equal-like clauses & "ORDER BY" relation table columns

- field/export_test.go
- field/string.go
> feat: implement function REPLACE/CONCAT

- internal/model/tbl_column.go
> fix: wrap blank default value tag

- README.ZH_CN.md
- README.md
- do.go
- generator_test.go
- helper/clause.go
- interface.go
- internal/template/struct.go
> feat: support join with sub query

- internal/template/method.go
FindByPage return all result when limit<=0
> feat: FindByPage return all result when limit<=0

- internal/model/base.go
> feat(generate): add real/numeric type mapping for sqlite

- internal/model/base.go
> style: remove tag's verbose space

- examples/cmd/from_object/prepare.go
- helper/object.go
- internal/check/gen_structs.go
> feat: add field's column name

- README.ZH_CN.md
- README.md
- config.go
- generator.go
- internal/check/gen_structs.go
- internal/model/base.go
- internal/model/conf.go
- internal/model/tbl_column.go
> feat: generate unsigned integer type

- internal/template/method.go
Description on issue #423 
Fix #423 
Use case on issue #423
> feature: model Joins & Preload methods support multiple RelationField

- internal/model/tbl_column.go
> fix: remove zero value default tag

- internal/model/tbl_column.go
> fix: int default tag without quote

- config.go
- internal/template/base.go
> style: format template

- internal/model/tbl_column.go
> fix: float default tag without quote

- internal/model/base.go
- internal/model/conf.go
- internal/model/tbl_column.go
> refactor: generate gorm default tag

- README.ZH_CN.md
- README.md
> docs: optimize

- .golangci.yml
- do.go
- do_test.go
- field/association.go
- field/bool.go
- field/doc.go
- field/export.go
- field/expr.go
- field/field.go
- field/float.go
- field/int.go
- field/string.go
- field/time.go
- generator.go
- tools/gentool/gentool.go
import golangci.yml && supply some comments
> style: optimize code style

- examples/main.go
close #446 
example/main.cpp: set sefault db for query
`go run example/main.go`
> example/main.cpp: set sefault db for query

- config.go
Fix variable names about file name
fix a typo
> style: fix typo

- internal/model/tbl_column.go
> fix: ignore zero value default tag

- field/function.go
> feat: support FromUnixTime

- internal/model/tbl_column.go
> fix: remove verbose quote for default tag

- go.mod
- go.sum
- sec_check.go
> fix: accept clause `dbresolver.Operation`

- internal/check/export.go
> feat: accept diy new struct name (#456)

- go.mod
- go.sum
- internal/check/tb_info.go
- internal/model/tbl_column.go
- internal/model/tbl_index.go
> feat: gen index

- README.ZH_CN.md
- README.md
- helper/clause.go
- internal/check/struct_test.go
- internal/parser/parser.go
> docs: add `AddMethod` doc

- internal/template/method.go
> fix: rename template variable name to avoid naming conflicts with package name

- config.go
> feat: accept file name without path

- internal/template/method.go
> fix: template field name

- internal/model/base.go
> fix: generate []byte field with query type field.Bytes

- internal/check/checkinterface.go
- internal/parser/parser.go
> fix：fix bytes->byte,and rename function name

- README.ZH_CN.md
- README.md
- config.go
- generator.go
> docs: introduce generate mode

- do.go
- do_test.go
- generator.go
- helper/clause.go
- internal/check/checkinterface.go
- internal/check/clause_test.go
- internal/check/export.go
- internal/model/base.go
- internal/model/conf.go
- internal/model/options.go
- internal/model/tbl_column.go
- internal/model/tbl_index.go
- internal/parser/parser.go
- internal/utils/common.go
> style: optimize

- do.go
- field/association.go
> feat: preload unscoped

- interface.go
> feat: add `Clauses` method to `Dao`

- internal/template/struct.go
> fix: many2many relationship typo

- internal/template/struct.go
> fix: template typo #523

- README.ZH_CN.md
- README.md
> docs: usage of diy method

- README.ZH_CN.md
- README.md
> docs: fix README typo

- export.go
- field_options.go
> style: remove export.go

- generator.go
> fix(generate): log out of range

- generator.go
> fix: log end Line out of range

- generator.go
- import.go
- internal/template/base.go
> fix(generate): import pkg path uniq

- field/association.go
- field/export.go
> feat: optimize AssociationFields for the association

- tools/gentool/README.ZH_CN.md
- tools/gentool/README.md
- tools/gentool/gen.yml
- tools/gentool/gentool.go
> 
使用gentool工具+yaml文件配置生成多张表时，一行文件过长。通过yaml list的方式能更好维护。增加生成数据类型配置参数。能根据数据表定义类型区分模型数据类型，和数据库保持一致。
> adjust generated data type

- sec_check.go
> feat(do): check detail for clause Insert

- README.ZH_CN.md
- README.md
update the usage of tool's flag "-c"
> feat: update README.md and README.ZH_CN.md

- README.ZH_CN.md
fix yml format error in README.ZH_CN.md
> docs: update README.ZH_CN.md

- README.ZH_CN.md
fix one typo in README.ZH_CN.md
> docs: fix typo in README.ZH_CN.md

- do.go
- interface.go
- internal/template/method.go
- internal/template/struct.go
receive delete model for association
> feat(do): delete receive models

- field/export_test.go
- field/expr.go
> feat: implement add/sub col expression

- do.go
> fix: Results are not returned on "Returning"

- internal/template/struct.go
> fix: gen inteface tmpl

- README.ZH_CN.md
- README.md
- field_options.go
- generator.go
- internal/generate/export.go
- internal/generate/generate.go
- internal/generate/query.go
- internal/generate/query_test.go
- internal/model/config.go
- internal/model/options.go
- internal/parser/export.go
- internal/template/model.go
> feat: add method opt

- field/export_test.go
- field/expr.go
> feat(field): column stream operate

- internal/model/tbl_column.go
close #593 
GORM fix this issue in https://github.com/go-gorm/gorm/commit/0097b39a77b9573d63f89c22f3cea0aae103a77f
> feat: allow default tag CURRENT_TIMESTAMP

- field/export_test.go
> tests: add field unit test

- generator.go
- internal/generate/export.go
> feat: ignore empty table

- .github/workflows/tests.yml
> chore(github): add go version

- do.go
> feat: update subquery with alias

- do_test.go
- field/asterisk.go
- field/export.go
- field/export_test.go
- generator_test.go
- internal/template/struct.go
> feat: add new field type Asterisk

- README.ZH_CN.md
- README.md
- field_options.go
- internal/generate/query.go
- internal/model/base.go
> feat: support custom field type

- README.ZH_CN.md
- README.md
…`AssociationFields`
#612 
Update: README.md and README.ZH_CN.md `AssociationsFields` Modify to `AssociationFields`
None
> docs: fix README.md and README.ZH_CN.md typo

- do.go
> style: log with error

- generator.go
- import.go
> fix:data race(#588)

- internal/template/model.go
- internal/template/struct.go
- tests/.expect/dal_1/query/users.gen.go
- tests/.expect/dal_2/query/users.gen.go
> feat: generate column comment in query struct

- internal/generate/export.go
- internal/generate/query.go
Reverts go-gorm/gen#616
fix #629  #632
> revert: "fix: ParseStructRelationShip with cache" (#616)

- README.ZH_CN.md
- README.md
- field_options.go
> feat: change method opt

- internal/template/struct.go
> fix: interface dao add method ReplaceDB

- README.md
> docs: optimize cases in documents

- internal/template/query.go
- internal/template/struct.go
- tests/.expect/dal_1/query/gen.go
- tests/.expect/dal_2/query/gen.go
- tests/.expect/dal_test/query/gen.go
> feat: add method for query (readDB/writeDB)

- README.ZH_CN.md
> docs: fix error in comment

- do.go
- do_options.go
- internal/template/query.go
- internal/template/struct.go
- tests/.expect/dal_1/query/banks.gen.go
- tests/.expect/dal_1/query/credit_cards.gen.go
- tests/.expect/dal_1/query/customers.gen.go
- tests/.expect/dal_1/query/gen.go
- tests/.expect/dal_1/query/people.gen.go
- tests/.expect/dal_1/query/users.gen.go
- tests/.expect/dal_2/query/banks.gen.go
- tests/.expect/dal_2/query/credit_cards.gen.go
- tests/.expect/dal_2/query/customers.gen.go
- tests/.expect/dal_2/query/gen.go
- tests/.expect/dal_2/query/people.gen.go
- tests/.expect/dal_2/query/users.gen.go
> feat: remove verbose schema &&  fix transaction

- generator.go
- [] Tested
Fixed file creation error caused by table synchronization in windows
> feature compatibility windows

- tests/test.sh
> fix: ignore -u flag

- do.go
> fix: replace conn pool

- do.go
> fix: replace db

- do.go
- internal/template/query.go
- tests/.expect/dal_1/query/gen.go
- tests/.expect/dal_2/query/gen.go
- tests/.expect/dal_3/query/gen.go
- tests/.expect/dal_test/query/gen.go
> fix: clone and write db

- do.go
- field/expr.go
- tests/go.mod
> Implement clause.Expression interface for field.Expr

- internal/template/query.go
- tests/.expect/dal_1/query/gen.go
- tests/.expect/dal_2/query/gen.go
- tests/.expect/dal_3/query/gen.go
- tests/.expect/dal_4/query/gen.go
> feat: return begin err

- field/time.go
> fix: fix field.Time IfNull accept param type

- field/time.go
implement `Year` function on `field.Time`
> feat(field): add func YEAR

- internal/generate/query.go
- internal/generate/section.go
> fix gen.WithMethod can't read current package

- field/expr.go
implement concat columns functions on field
> feat: implement concat columns

- field/string.go
implement `SUBSTRING_INDEX` for field String/Bytes
> feat: implement SUBSTRING_INDEX for field String/Bytes

- field/expr.go
add `ConcatCol` to `field.Expr` interface
> feat: update Expr interface

- config.go
- examples/cmd/sync_table/generate.go
- examples/cmd/ultimate/generate.go
- internal/model/config.go
- internal/model/tbl_column.go
> feat: support type mapping by colume

- config.go
- generator.go
> fix: path separator

- config.go
- do_test.go
- examples/cmd/from_object/prepare.go
- field/association.go
- field/tag.go
- field_options.go
- generator.go
- helper/object.go
- internal/generate/export.go
- internal/generate/generate.go
- internal/model/base.go
- internal/model/config.go
- internal/model/tbl_column.go
- internal/template/model.go
- tests/.expect/dal_1/model/users.gen.go
- tests/.expect/dal_2/model/users.gen.go
- tests/.expect/dal_3/model/users.gen.go
- tests/.expect/dal_4/model/users.gen.go
- tests/.expect/dal_test/model/users.gen.go
> feat: field tag

- internal/parser/parser.go
> support two-dimensional array

- do.go
This MR will fully parse order expression value without  leaving any placeholder '?' for prepare statement.
> feat: fully parse order value

- examples/cmd/from_object/prepare.go
- field/association.go
- field/tag.go
- field_options.go
- internal/generate/export.go
- internal/model/tbl_column.go
- internal/template/model.go
- tests/.expect/dal_1/model/users.gen.go
- tests/.expect/dal_2/model/users.gen.go
- tests/.expect/dal_3/model/users.gen.go
- tests/.expect/dal_4/model/users.gen.go
- tests/generate_test.go
generate model struct with golang comment and some optimizations
> fix: add field comment

- tools/gentool/gentool.go
1，执行 gentool  -outPath "./dao/query"  参数时候无效，会在当前目录下生成.
2，config参数格式配置错误的时候没有打印err
> fix: flag outPath and  config error log

- field/tag.go
- go.mod
- go.sum
- internal/model/tbl_column.go
- tests/.expect/dal_2/model/users.gen.go
- tests/.expect/dal_3/model/users.gen.go
- tests/.expect/dal_4/model/users.gen.go
- tests/tables.sql
> fix: gorm tag of multi index

- internal/template/struct.go
- tests/.expect/dal_1/query/banks.gen.go
- tests/.expect/dal_1/query/credit_cards.gen.go
- tests/.expect/dal_1/query/customers.gen.go
- tests/.expect/dal_1/query/people.gen.go
- tests/.expect/dal_1/query/users.gen.go
- tests/.expect/dal_2/query/banks.gen.go
- tests/.expect/dal_2/query/credit_cards.gen.go
- tests/.expect/dal_2/query/customers.gen.go
- tests/.expect/dal_2/query/people.gen.go
- tests/.expect/dal_2/query/users.gen.go
- tests/.expect/dal_3/query/banks.gen.go
- tests/.expect/dal_3/query/credit_cards.gen.go
- tests/.expect/dal_3/query/customers.gen.go
- tests/.expect/dal_3/query/people.gen.go
- tests/.expect/dal_3/query/users.gen.go
- tests/.expect/dal_4/query/banks.gen.go
- tests/.expect/dal_4/query/credit_cards.gen.go
- tests/.expect/dal_4/query/customers.gen.go
- tests/.expect/dal_4/query/people.gen.go
- tests/.expect/dal_4/query/users.gen.go
> feat: add columns method

- field_options.go
> WIP: feat: implement field diy modify

- do.go
- internal/template/method.go
> implement gen.Exists method

- internal/template/method.go
- tests/.expect/dal_1/query/banks.gen.go
- tests/.expect/dal_1/query/credit_cards.gen.go
- tests/.expect/dal_1/query/customers.gen.go
- tests/.expect/dal_1/query/people.gen.go
- tests/.expect/dal_1/query/users.gen.go
- tests/.expect/dal_2/query/banks.gen.go
- tests/.expect/dal_2/query/credit_cards.gen.go
- tests/.expect/dal_2/query/customers.gen.go
- tests/.expect/dal_2/query/people.gen.go
- tests/.expect/dal_2/query/users.gen.go
- tests/.expect/dal_3/query/banks.gen.go
- tests/.expect/dal_3/query/credit_cards.gen.go
- tests/.expect/dal_3/query/customers.gen.go
- tests/.expect/dal_3/query/people.gen.go
- tests/.expect/dal_3/query/users.gen.go
- tests/.expect/dal_4/query/banks.gen.go
- tests/.expect/dal_4/query/credit_cards.gen.go
- tests/.expect/dal_4/query/customers.gen.go
- tests/.expect/dal_4/query/people.gen.go
- tests/.expect/dal_4/query/users.gen.go
- tests/.expect/dal_5/model/users.gen.go
- tests/.expect/dal_5/query/users.gen.go
- tests/.expect/dal_6/model/users.gen.go
- tests/.expect/dal_6/query/users.gen.go
- tests/.expect/dal_test/query/banks.gen.go
- tests/.expect/dal_test/query/credit_cards.gen.go
- tests/.expect/dal_test/query/customers.gen.go
- tests/.expect/dal_test/query/people.gen.go
- tests/.expect/dal_test/query/users.gen.go
> feat: test

- field/expr.go
> feat: add abs func

- do.go
- field/assign_attr.go
- field/expr.go
> feat: assign or attr map/struct

- internal/template/method.go
- tests/.expect/dal_2/query/banks.gen_test.go
- tests/.expect/dal_2/query/credit_cards.gen_test.go
- tests/.expect/dal_2/query/customers.gen_test.go
- tests/.expect/dal_2/query/people.gen_test.go
- tests/.expect/dal_2/query/users.gen_test.go
- tests/.expect/dal_3/query/banks.gen_test.go
- tests/.expect/dal_3/query/credit_cards.gen_test.go
- tests/.expect/dal_3/query/customers.gen_test.go
- tests/.expect/dal_3/query/people.gen_test.go
- tests/.expect/dal_3/query/users.gen_test.go
- tests/.expect/dal_4/query/banks.gen_test.go
- tests/.expect/dal_4/query/credit_cards.gen_test.go
- tests/.expect/dal_4/query/customers.gen_test.go
- tests/.expect/dal_4/query/people.gen_test.go
- tests/.expect/dal_4/query/users.gen_test.go
- tests/.expect/dal_5/query/users.gen_test.go
- tests/.expect/dal_6/query/users.gen_test.go
replace `clause.PrimaryKey` to `id` for join unit test
> fix: fix unit_test join pk error

- field/function.go
- #811 
- To implement order by rand()
> feat: add rand function #811

- tools/gentool/gentool.go
> feat: tool config

- internal/generate/export.go
- internal/generate/query.go
- internal/generate/table.go
- internal/template/struct.go
> feat: table comment

- .github/workflows/reviewdog.yml
> chore(github): set golangci-lint flag timeout to 5mins

- field/export_test.go
add unit test for `field.ALL.Count().As("num")`
> test: add field.ALL.Count().As() unit test

- field/export_test.go
> test: remove verbose unit test

- generator.go
> fix: add import pkg paths to single query files (#1032)

- .github/workflows/tests.yml
> chore(github): add unit test for go 1.20 and 1.21

- internal/template/method.go
fix generate error, when diy method without return param
> fix: remove assert code when result param is empty

- .github/workflows/tests.yml
> chore(github): ignore push check except master

- field/float.go
- field/int.go
- field/string.go
> fix!: method Filed should be Field

- field/tag.go
> feat: empty tag value

- field/assign_attr.go
- field/tag.go
Just improving simplify range expression
> style(field): simplify range expression

- generator.go
> style: replace from `io/ioutil` to `os`

- internal/model/tbl_column.go
> feat: fix scan type nil
